import {
  Tv,
  Volume2,
  Palette,
  Ruler,
  TrendingUp,
  Layers,
  CreditCard,
  DollarSign,
  Coins,
  Tag,
  BarChart3,
  Utensils,
  UtensilsCrossed,
  Beef,
  Flame,
  Soup,
  Pizza,
  Croissant,
  GlassWater,
  Coffee,
  Beer,
  Wine,
  Grape,
  Apple,
  Cherry,
  Carrot,
  Leaf,
  Circle,
  Egg,
  CupSoda,
  Candy,
  Cake,
  Dessert,
  Cookie,
  Backpack,
  Briefcase,
  Plane,
  Folder,
  Pill,
  Activity,
  Sparkles,
  Scissors,
  Key,
  Bed,
  Bath,
  Map,
  Compass,
  Train,
  Car,
  Bike,
  Footprints,
  User,
  Users,
  Smartphone,
  Calendar,
  Clock,
  Battery,
  Plug,
  Printer,
  Ticket,
  Award,
  Dribbble,
  Target,
  Mic,
  Headphones,
  Music,
  Radio,
  Wifi,
  Lightbulb,
  Zap,
  Search,
  Wrench,
  Hammer,
  Nut,
  Settings,
  Shield,
  Notebook,
  Globe,
  Rocket,
  Ship,
  Scale,
  Link,
  Gem,
  Thermometer,
  Dog,
  Cat,
  Bug,
  Turtle,
  Fish,
  Star,
  Moon,
  Mountain,
  Tent,
  Trees,
  Sprout,
  Flower,
  Cloud,
  Wind,
  RotateCw,
  Umbrella,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  Snowflake,
  Plus,
  Shuffle,
  X,
  Check,
  ArrowDown,
  ArrowUp,
  ArrowLeft,
  ArrowRight,
  HelpCircle,
  ArrowLeftRight,
  RefreshCw,
  MapPin,
  Heart,
  Hourglass,
  Trophy,
  Smile,
  Frown,
  Inbox,
  Bell,
  AlertTriangle,
  Box,
  MessageSquare
} from "lucide-react";

interface EmojiIconProps {
  emoji: string;
  className?: string;
  size?: number;
}

// Map emojis directly to corresponding Lucide Icon components
const emojiMap: Record<string, any> = {
  // Superlatives / Feelings / People
  "😌": Smile,
  "😰": Frown,
  "😊": Smile,
  "😍": Heart,
  "💗": Heart,
  "😔": Frown,
  "😁": Smile,
  "👍": Check,
  "👎": X,
  "👤": User,
  "👥": Users,
  "👫": Users,
  "🙋": User,
  "🙋‍♀️": User,
  "🤵": User,
  "👩‍💼": User,
  "😴": Moon,
  "🙄": HelpCircle,
  "🤔": HelpCircle,
  "🤷": HelpCircle,
  "⏳": Hourglass,
  "👀": Search,

  // Travel / Hotel / Items
  "🩹": Activity,
  "💊": Pill,
  "🧪": Notebook,
  "🤢": Frown,
  "☁️": Cloud,
  "🔴": Sparkles,
  "🧥": Layers,
  "👔": User,
  "👕": Layers,
  "🧶": Layers,
  "👖": Layers,
  "🩱": Layers,
  "🌙": Moon,
  "🩳": Layers,
  "👠": Footprints,
  "👟": Footprints,
  "🪪": CreditCard,
  "🖊️": Ruler,
  "📅": Calendar,
  "🗓️": Calendar,
  "📷": Tv,
  "🔋": Battery,
  "📚": Notebook,
  "📗": Notebook,
  "🔵": Circle,
  "🦷": Sparkles,
  "🪥": Sparkles,
  "💨": Wind,
  "🧼": Sparkles,
  "🏊": Sprout,
  "💼": Briefcase,
  "🛎️": Bell,
  "🧹": Sparkles,
  "🚪": Key,
  "📋": Notebook,
  "🛌": Bed,
  "🧣": Layers,
  "🌊": RotateCw,
  "🚗": Car,

  // Shopping / Money
  "📺": Tv,
  "🔊": Volume2,
  "🎨": Palette,
  "📏": Ruler,
  "📈": TrendingUp,
  "💳": CreditCard,
  "💵": DollarSign,
  "📊": BarChart3,
  "💰": Coins,
  "🏷️": Tag,
  "🔍": Search,
  "❌": X,
  "✅": Check,
  "📝": Notebook,

  // Food / Locations / Eating out
  "🍖": Beef,
  "🥩": Beef,
  "🍕": Pizza,
  "🥪": Utensils,
  "☕": Coffee,
  "🥐": Croissant,
  "🍽️": UtensilsCrossed,
  "🏺": GlassWater,
  "🍝": Soup,
  "🍩": Dessert,
  "🍪": Cookie,
  "🧁": Dessert,
  "🥗": Leaf,
  "🍲": Soup,
  "🥛": GlassWater,
  "🥤": CupSoda,
  "🍹": Wine,
  "🍷": Wine,
  "🍻": Beer,
  "🍺": Beer,
  "🥃": GlassWater,
  "🥣": Soup,
  "🥧": Cake,
  "🥔": Sparkles,
  "🥕": Carrot,
  "🧅": Leaf,
  "🌽": Leaf,
  "🌾": Sprout,
  "🌴": Trees,
  "🫑": Leaf,
  "🟢": Circle,
  "🟡": Circle,
  "🟣": Circle,
  "🍇": Grape,
  "🍉": Grape,
  "🍌": Smile,
  "🥭": Apple,
  "🍎": Apple,
  "🍒": Cherry,
  "🍓": Cherry,
  "🍍": Apple,
  "🍏": Apple,
  "🍐": Apple,
  "🥑": Apple,
  "🐖": Dog,
  "🐷": Coins,
  "🐓": Egg,
  "🦃": Egg,
  "🦆": Egg,
  "🐟": Fish,
  "🍳": Egg,
  "🍞": Layers,
  "🧈": Layers,
  "🫙": Box,
  "🍧": Dessert,
  "🍦": Dessert,
  "🍨": Dessert,
  "pancakes": Layers,
  "🥞": Layers,
  "🍬": Candy,
  "🍫": Layers,
  "🍑": Apple,

  // Abstract grammar / conjugations / verbs
  "⚠️": AlertTriangle,
  "📢": Volume2,
  "💬": MessageSquare,
  "🔌": Plug,
  "💡": Lightbulb,
  "🔮": Sparkles,
  "🔗": Link,
  "🏆": Trophy,
  "🔽": ArrowDown,
  "⭐": Star,
  "✨": Sparkles,
  "💔": Heart,
  "⚡": Zap,
  "🤝": Users,
  "📥": Inbox,
  "🔄": RefreshCw,
  "➕": Plus,
  "🔀": Shuffle,
  "📍": MapPin,
  "🎯": Target,
  "💪": Activity,
  "🎟️": Ticket
};

// Fallback logic to render the minimalist vector stroke icon
export function EmojiIcon({ emoji, className = "", size = 28 }: EmojiIconProps) {
  // Strip any whitespace/html entities if needed
  const cleanEmoji = emoji ? emoji.trim() : "";

  // Find exact match or use keyword fallback
  let IconComponent = emojiMap[cleanEmoji];

  if (!IconComponent) {
    if (cleanEmoji === "🛎️") IconComponent = Bell;
    else if (cleanEmoji === "🪪") IconComponent = CreditCard;
    else if (cleanEmoji === "🏠" || cleanEmoji === "🏨" || cleanEmoji === "🏪") IconComponent = Globe;
    else if (cleanEmoji === "🚿" || cleanEmoji === "Shower") IconComponent = Bath;
    else if (cleanEmoji === "🏖️" || cleanEmoji === "🏊") IconComponent = RotateCw;
    else if (cleanEmoji === "&#x1F604;") IconComponent = Smile;
    else {
      // General fallbacks based on visual types
      if (cleanEmoji.includes("☕") || cleanEmoji.includes("🥛") || cleanEmoji.includes("🥤")) {
        IconComponent = Coffee;
      } else if (cleanEmoji.includes("🥩") || cleanEmoji.includes("🍖") || cleanEmoji.includes("🐟") || cleanEmoji.includes("🍔")) {
        IconComponent = Beef;
      } else if (cleanEmoji.includes("🥐") || cleanEmoji.includes("🍞") || cleanEmoji.includes("🥖")) {
        IconComponent = Croissant;
      } else if (cleanEmoji.match(/^[aeiouAEIOU]/)) {
        IconComponent = Apple;
      } else {
        IconComponent = Sparkles;
      }
    }
  }

  return (
    <IconComponent
      size={size}
      className={`stroke-[1.6] fill-none text-[var(--accent)] transition-all duration-300 ${className}`}
    />
  );
}
